FROM golang:1.23.4 AS build-stage

WORKDIR /app
COPY go.mod ./
#COPY go.sum ./
RUN go mod download

COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

# run test
FROM build-stage AS run-test-stage
RUN go test -v ./..

# deploy
FROM gcr.io/distroless/static-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /docker-gs-ping /docker-gs-ping

EXPOSE 8088

USER nonroot:nonroot

ENTRYPOINT ["/docker-gs-ping"]